name: project_attendance
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  flutter_map_location_marker: ^9.1.0
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  equatable: ^2.0.5
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
  #   - images/a_dot_ham.jpeg
